version: '3.4'

services:
  vogcodechallenge.api:
    image: ${DOCKER_REGISTRY-}vogcodechallenge
    build:
      context: .
      dockerfile: VogCodeChallenge.API/Dockerfile
    environment:
      ASPNETCORE_ConnectionStrings__MSSQL: "Server=mssqlsrv,1433;Database=VogCodeChallenge.Database;User Id=sa;Password=Password123"
    depends_on:
      - mssqlsrv

  #ports: host:container
  mssqlsrv:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    container_name: challengeDB
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"